<?php
$seoTitle='Nossas Lojas | AserNet IoT Services';
$seoDescription='Encontre a loja AserNet mais próxima e conte com atendimento presencial, consultores especializados e suporte local.';
$stores=[
[1,'Loja Centro','R. Coronel João Cândido, 123','Centro - Três Corações/MG','R. Coronel Joao Candido 123 Tres Coracoes MG'],
[2,'Loja Nova Três Corações','Av. Rei Pelé, 620','Nova Três Corações - Três Corações/MG','Av. Rei Pele 620 Tres Coracoes MG'],
[3,'Loja Santa Rita','Rua Deputado Renato Azeredo, 210','Santa Rita do Sapucaí/MG','Rua Deputado Renato Azeredo 210 Santa Rita do Sapucai MG'],
[4,'Loja Cambuí','Av. José Álvares Maciel, 96','Cambuí/MG','Av. Jose Alvares Maciel 96 Cambui MG'],
[5,'Loja Pouso Alegre','Av. Prefeito Sapucaí, 1099','Pouso Alegre/MG','Av. Prefeito Sapucai 1099 Pouso Alegre MG']];
$icons=['icon-wifi','icon-mobile-phone','icon-phone','icon-casino-cctv','icon-office','icon-security'];
?>
<!DOCTYPE html><html lang="pt-BR"><head><title>AserNet - Nossas Lojas</title><?php include ROOT.'/includes/assets.php';?></head><body>
<?php include ROOT.'/includes/header/header.php';?>
<main class="stores"><section class="stores__hero"><div class="container"><div class="row align-items-center"><div class="col-lg-5 col-md-7"><div class="stores__hero-copy"><h1>Encontre a <strong>AserNet</strong> mais perto de você.</h1><p>Atendimento presencial, consultores especializados e suporte local para sua casa ou empresa.</p><ul class="stores__hero-benefits"><li><i class="icon-group"></i><span><strong>Atendimento humano</strong>Nossa equipe está pronta para te receber.</span></li><li><i class="icon-security"></i><span><strong>Soluções completas</strong>Internet, Wi-Fi, móvel, câmeras, segurança e muito mais.</span></li></ul></div></div><div class="col-lg-7 col-md-5"></div></div></div></section>
<section class="stores__locations"><div class="container"><header class="stores__heading"><h2>Nossas lojas</h2><p>Visite uma de nossas unidades e descubra a melhor solução para você.</p></header><div class="row stores__grid">
<?php foreach($stores as $store):?><div class="col-lg-4 col-md-6 stores__column"><article class="stores__card"><div class="stores__card-image stores__card-image--<?=$store[0]?>" role="img" aria-label="Fachada da <?=htmlspecialchars($store[1])?>"></div><div class="stores__card-body"><div class="stores__card-title"><b><?=$store[0]?></b><h3><?=htmlspecialchars($store[1])?></h3></div><div class="stores__info"><i class="icon-pin"></i><p><?=htmlspecialchars($store[2])?><br><?=htmlspecialchars($store[3])?></p></div><div class="stores__info"><i class="icon-clock"></i><p>Seg a Sex: 8h às 18h<br>Sáb: 8h às 12h</p></div><div class="stores__actions"><a href="https://www.google.com/maps/search/?api=1&amp;query=<?=urlencode($store[4])?>" target="_blank" rel="noopener"><i class="icon-carpin"></i>Como chegar</a><a class="stores__whatsapp" href="https://wa.me/5508002225262" target="_blank" rel="noopener"><i class="icon-whatsapp"></i>WhatsApp</a></div><div class="stores__services"><span>Serviços disponíveis</span><div><?php foreach($icons as $icon):?><i class="<?=$icon?>"></i><?php endforeach;?></div></div></div></article></div><?php endforeach;?>
<div class="col-lg-4 col-md-6 stores__column"><aside class="stores__expansion"><i class="icon-office stores__expansion-icon"></i><h2>Hoje são 5 lojas.<br><strong>Em breve, ainda<br>mais perto de você.</strong></h2><p>Nosso projeto é chegar a 10 lojas nos próximos 2 anos, levando tecnologia, atendimento e confiança para ainda mais cidades.</p><div class="stores__route"><i class="icon-pin"></i><span></span><i class="icon-pin"></i><span></span><i class="icon-pin"></i><i class="icon-office"></i></div></aside></div></div>
<section class="stores__closing"><div class="stores__closing-image" role="img" aria-label="Família conectada com soluções AserNet"></div><div class="stores__closing-copy"><h2>A tecnologia evolui.<br>O atendimento local continua<br>sendo nosso <strong>diferencial.</strong></h2><p>Conte com a AserNet para conectar, proteger e simplificar sua vida com soluções inteligentes e atendimento de verdade.</p></div><div class="stores__closing-map"><i class="icon-pin"></i><i class="icon-pin"></i><i class="icon-pin"></i><i class="icon-pin"></i><i class="icon-pin"></i></div></section></div></section></main>
<?php include ROOT.'/includes/footer/footer.php';?><?php include ROOT.'/includes/scripts.php';?></body></html>